on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:

      - name: ğŸš€ Job triggered by a ${{ github.event_name }}.
        run: echo "ğŸš€ Job triggered by a ${{ github.event_name }}."

      - name: ğŸ›’ Checkout source Git branch
        uses: actions/checkout@v4
        with:
            ref: main
            fetch-depth: 10
            submodules: true

      - name: ğŸš® Remove sourcemapped CSS.
        run: rm css -r
      
      - name: ğŸª„ Make a new production CSS directory
        run: mkdir css

      - name: ğŸ—œï¸ Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: sass/damn.scss
          destination: css/damn.css
      
      - name: ğŸ«  This job's status is ${{ job.status }}.
        run: echo "ğŸ«  This job's status is ${{ job.status }}."